# Server-side connect-go exposure (issue #912 slice 2): a
# `New<Stem>Handler(impl)` wiring call marks the impl type's contract methods
# as EXPOSING the same unscoped `resource::RPC::<Stem>.<Method>` nodes that
# client sinks target, so caller and server join on one resource node.
from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

from codebase_rag import constants as cs
from codebase_rag.capture import resolve_capture
from codebase_rag.graph_updater import GraphUpdater
from codebase_rag.parser_loader import load_parsers

EXPOSES = cs.RelationshipType.EXPOSES.value
_CAPTURE_IO = resolve_capture([cs.CaptureGroup.IO.value])

_CONNECT_GEN = (
    "package userv1connect\n\n"
    "type UserServiceHandler interface {\n"
    "\tGetUser(id string) error\n"
    "\tPutUser(id string) error\n"
    "}\n\n"
    "func NewUserServiceHandler(svc UserServiceHandler) (string, int) {\n"
    '\treturn "", 0\n'
    "}\n"
)


def _run_exposes(tmp_path: Path, files: dict[str, str]) -> set[tuple[str, str]]:
    # Build the graph for `files` and return (source_qn, resource_qn) for
    # EXPOSES edges only.
    parsers, queries = load_parsers()
    for rel, content in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    mock = MagicMock()
    GraphUpdater(
        ingestor=mock,
        repo_path=tmp_path,
        parsers=parsers,
        queries=queries,
        capture=_CAPTURE_IO,
    ).run()
    return {
        (c.args[0][2], c.args[2][2])
        for c in mock.ensure_relationship_batch.call_args_list
        if str(c.args[1]) == EXPOSES
    }


def test_ctor_bound_impl_exposes_contract_methods(tmp_path: Path) -> None:
    # The verified production shape: the impl comes from a cross-package
    # constructor and the generated package is imported under an alias.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svc/server.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func (s *Server) PutUser(id string) error {\n\treturn nil\n}\n\n"
            "func (s *Server) Extra() {}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import userv1 "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svc"\n\n'
            "func main() {\n"
            "\tuSrv := server.New()\n"
            "\tpath, handler := userv1.NewUserServiceHandler(uSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    impl = f"{project}.svc.server.Server"
    assert (f"{impl}.GetUser", "resource::RPC::UserService.GetUser") in rels, rels
    assert (f"{impl}.PutUser", "resource::RPC::UserService.PutUser") in rels, rels
    # An exported method outside the generated contract is not an RPC.
    assert not any(src == f"{impl}.Extra" for src, _r in rels), rels


def test_composite_literal_impl_exposes(tmp_path: Path) -> None:
    # The impl bound from a composite literal in the wiring function itself.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\timpl := &Impl{}\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(impl)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels
    # PutUser is in the contract but the impl does not define it: no edge.
    assert not any(res.endswith("PutUser") for _s, res in rels), rels


def test_non_connect_handler_ctor_is_not_rpc(tmp_path: Path) -> None:
    # `New<Stem>Handler` from a package NOT generated by connect-go carries no
    # contract evidence.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "web/handlers.go": (
            "package web\n\n"
            "type UserServiceHandler interface {\n\tGetUser(id string) error\n}\n\n"
            "func NewUserServiceHandler(svc UserServiceHandler) int {\n\treturn 0\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/web"\n\n'
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\timpl := &Impl{}\n"
            "\th := web.NewUserServiceHandler(impl)\n"
            "\t_ = h\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    assert not any("resource::RPC::" in res for _s, res in rels), rels


def test_multi_return_ctor_binding_exposes(tmp_path: Path) -> None:
    # `grpcSrv, err := grpc.New(...)` (the second verified wiring shape):
    # the call value types the first bound name.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "grpc/grpc.go": (
            "package grpc\n\n"
            "type GRPCServer struct{}\n\n"
            "func New() (*GRPCServer, error) {\n\treturn &GRPCServer{}, nil\n}\n\n"
            "func (g *GRPCServer) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/grpc"\n\n'
            "func main() {\n"
            "\tgrpcSrv, err := grpc.New()\n"
            "\t_ = err\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(grpcSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.grpc.grpc.GRPCServer.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_shadowed_qualifier_is_not_a_wiring(tmp_path: Path) -> None:
    # A local shadowing the imported package name makes the call a method on
    # the LOCAL value, not connect-go wiring (mirrors the client-side guard).
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Faker struct{}\n\n"
            "func (f Faker) NewUserServiceHandler(v any) (string, int) {\n"
            '\treturn "", 0\n'
            "}\n\n"
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\timpl := &Impl{}\n"
            "\tuserv1connect := Faker{}\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(impl)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    assert not any("resource::RPC::" in res for _s, res in rels), rels


def test_inline_composite_literal_arg_exposes(tmp_path: Path) -> None:
    # The impl passed inline: `NewUserServiceHandler(&Impl{})`.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_inline_ctor_call_arg_exposes(tmp_path: Path) -> None:
    # The impl constructed inline: `NewUserServiceHandler(server.New())`.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svc/server.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svc"\n\n'
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(server.New())\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.svc.server.Server.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_ambiguous_clause_fallback_stays_silent(tmp_path: Path) -> None:
    # TWO imported directories both declare `package server`; the unaliased
    # qualifier cannot be attributed, so no edge is emitted rather than a
    # guess against whichever import iterates first.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svca/impl.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "svcb/impl.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svca"\n'
            'import "example.com/app/svcb"\n\n'
            "func main() {\n"
            "\tuSrv := server.New()\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(uSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    assert not any("resource::RPC::" in res for _s, res in rels), rels


def test_clause_named_package_ctor_resolves(tmp_path: Path) -> None:
    # An unaliased import's qualifier is the target's `package` clause, which
    # may differ from the directory name (`svc/` declaring `package server`):
    # the import-map key is the path segment, so resolution must fall back to
    # matching the clause recorded for the imported package's modules.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svc/impl.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svc"\n\n'
            "func main() {\n"
            "\tuSrv := server.New()\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(uSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.svc.impl.Server.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels
