"""Graph-aware editing primitives: span-preserving patchers (issue #1529),
transactions (issue #1528) and import rewriting (issue #1530)."""

from .contract import (
    Expectation,
    Verdict,
    change_signature_expectation,
    measure,
    move_expectation,
    rename_expectation,
    verify,
)
from .imports import ImportRewriter, ImportSite, Rewrite, RewriteError, SymbolMove
from .patcher import (
    Patcher,
    PatcherError,
    PatchResult,
    SpanEdit,
    apply_span_edits,
    byte_to_line_col,
    formatter_check,
    line_col_to_byte,
)
from .transaction import (
    EditTransaction,
    StagedFile,
    StagedTree,
    TransactionConflict,
    TransactionError,
    TransactionOutcome,
    VerificationResult,
    transaction,
    undo_last,
    undo_transaction,
)

__all__ = [
    "Expectation",
    "Verdict",
    "change_signature_expectation",
    "measure",
    "move_expectation",
    "rename_expectation",
    "verify",
    "EditTransaction",
    "ImportRewriter",
    "ImportSite",
    "PatchResult",
    "Patcher",
    "PatcherError",
    "Rewrite",
    "RewriteError",
    "SpanEdit",
    "StagedFile",
    "StagedTree",
    "SymbolMove",
    "TransactionConflict",
    "TransactionError",
    "TransactionOutcome",
    "VerificationResult",
    "apply_span_edits",
    "byte_to_line_col",
    "formatter_check",
    "line_col_to_byte",
    "transaction",
    "undo_last",
    "undo_transaction",
]
