name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Run command '...'
        2. Parse repository '...'
        3. Query with '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The query should return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, it returned an error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs
      render: shell
      placeholder: Paste error logs here

  - type: dropdown
    id: language
    attributes:
      label: Programming Language
      description: Which language(s) were you analyzing when the bug occurred?
      multiple: true
      options:
        - Python
        - C++
        - Java
        - JavaScript
        - TypeScript
        - Rust
        - Lua
        - C#
        - Go
        - PHP
        - Scala
        - Other/Not Applicable

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Code-Graph-RAG are you using?
      placeholder: "0.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on?
      options:
        - macOS
        - Linux
        - Windows
        - WSL
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "Python 3.12.0"
    validations:
      required: true

  - type: dropdown
    id: llm-provider
    attributes:
      label: LLM Provider
      description: Which LLM provider are you using?
      options:
        - Google Gemini
        - OpenAI
        - Ollama (local)
        - Not Applicable

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help
      placeholder: Add any other context about the problem here

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant error logs and steps to reproduce
          required: true
        - label: I am using a supported version of Python (3.12+)
          required: true
