"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GraphCodeIndex(google.protobuf.message.Message):
    """=======================================================
    Top-Level Container Message
    =======================================================
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODES_FIELD_NUMBER: builtins.int
    RELATIONSHIPS_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Node]: ...
    @property
    def relationships(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Relationship]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Iterable[global___Node] | None = ...,
        relationships: collections.abc.Iterable[global___Relationship] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nodes", b"nodes", "relationships", b"relationships"]) -> None: ...

global___GraphCodeIndex = GraphCodeIndex

@typing.final
class Node(google.protobuf.message.Message):
    """=======================================================
    Generic Node and Relationship Messages
    =======================================================

    A generic container for any node in the graph.
    The 'oneof' field holds the specific, strongly-typed payload.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_FIELD_NUMBER: builtins.int
    PACKAGE_FIELD_NUMBER: builtins.int
    FOLDER_FIELD_NUMBER: builtins.int
    MODULE_FIELD_NUMBER: builtins.int
    CLASS_FIELD_NUMBER: builtins.int
    FUNCTION_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    FILE_FIELD_NUMBER: builtins.int
    EXTERNAL_PACKAGE_FIELD_NUMBER: builtins.int
    MODULE_IMPLEMENTATION_FIELD_NUMBER: builtins.int
    MODULE_INTERFACE_FIELD_NUMBER: builtins.int
    @property
    def project(self) -> global___Project: ...
    @property
    def package(self) -> global___Package: ...
    @property
    def folder(self) -> global___Folder: ...
    @property
    def module(self) -> global___Module: ...
    @property
    def function(self) -> global___Function: ...
    @property
    def method(self) -> global___Method: ...
    @property
    def file(self) -> global___File: ...
    @property
    def external_package(self) -> global___ExternalPackage: ...
    @property
    def module_implementation(self) -> global___ModuleImplementation: ...
    @property
    def module_interface(self) -> global___ModuleInterface: ...
    def __init__(
        self,
        *,
        project: global___Project | None = ...,
        package: global___Package | None = ...,
        folder: global___Folder | None = ...,
        module: global___Module | None = ...,
        function: global___Function | None = ...,
        method: global___Method | None = ...,
        file: global___File | None = ...,
        external_package: global___ExternalPackage | None = ...,
        module_implementation: global___ModuleImplementation | None = ...,
        module_interface: global___ModuleInterface | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["class", b"class", "external_package", b"external_package", "file", b"file", "folder", b"folder", "function", b"function", "method", b"method", "module", b"module", "module_implementation", b"module_implementation", "module_interface", b"module_interface", "package", b"package", "payload", b"payload", "project", b"project"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["class", b"class", "external_package", b"external_package", "file", b"file", "folder", b"folder", "function", b"function", "method", b"method", "module", b"module", "module_implementation", b"module_implementation", "module_interface", b"module_interface", "package", b"package", "payload", b"payload", "project", b"project"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["project", "package", "folder", "module", "class", "function", "method", "file", "external_package", "module_implementation", "module_interface"] | None: ...

global___Node = Node

@typing.final
class Relationship(google.protobuf.message.Message):
    """Represents a single, directed relationship between two nodes.
    The source and target IDs are the primary keys of the respective nodes.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RelationshipType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RelationshipTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Relationship._RelationshipType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        RELATIONSHIP_TYPE_UNSPECIFIED: Relationship._RelationshipType.ValueType  # 0
        CONTAINS_PACKAGE: Relationship._RelationshipType.ValueType  # 1
        CONTAINS_FOLDER: Relationship._RelationshipType.ValueType  # 2
        CONTAINS_FILE: Relationship._RelationshipType.ValueType  # 3
        CONTAINS_MODULE: Relationship._RelationshipType.ValueType  # 4
        DEFINES: Relationship._RelationshipType.ValueType  # 5
        DEFINES_METHOD: Relationship._RelationshipType.ValueType  # 6
        IMPORTS: Relationship._RelationshipType.ValueType  # 7
        INHERITS: Relationship._RelationshipType.ValueType  # 8
        OVERRIDES: Relationship._RelationshipType.ValueType  # 9
        CALLS: Relationship._RelationshipType.ValueType  # 10
        DEPENDS_ON_EXTERNAL: Relationship._RelationshipType.ValueType  # 11
        IMPLEMENTS_MODULE: Relationship._RelationshipType.ValueType  # 12
        IMPLEMENTS: Relationship._RelationshipType.ValueType  # 13

    class RelationshipType(_RelationshipType, metaclass=_RelationshipTypeEnumTypeWrapper): ...
    RELATIONSHIP_TYPE_UNSPECIFIED: Relationship.RelationshipType.ValueType  # 0
    CONTAINS_PACKAGE: Relationship.RelationshipType.ValueType  # 1
    CONTAINS_FOLDER: Relationship.RelationshipType.ValueType  # 2
    CONTAINS_FILE: Relationship.RelationshipType.ValueType  # 3
    CONTAINS_MODULE: Relationship.RelationshipType.ValueType  # 4
    DEFINES: Relationship.RelationshipType.ValueType  # 5
    DEFINES_METHOD: Relationship.RelationshipType.ValueType  # 6
    IMPORTS: Relationship.RelationshipType.ValueType  # 7
    INHERITS: Relationship.RelationshipType.ValueType  # 8
    OVERRIDES: Relationship.RelationshipType.ValueType  # 9
    CALLS: Relationship.RelationshipType.ValueType  # 10
    DEPENDS_ON_EXTERNAL: Relationship.RelationshipType.ValueType  # 11
    IMPLEMENTS_MODULE: Relationship.RelationshipType.ValueType  # 12
    IMPLEMENTS: Relationship.RelationshipType.ValueType  # 13

    TYPE_FIELD_NUMBER: builtins.int
    SOURCE_ID_FIELD_NUMBER: builtins.int
    TARGET_ID_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    SOURCE_LABEL_FIELD_NUMBER: builtins.int
    TARGET_LABEL_FIELD_NUMBER: builtins.int
    type: global___Relationship.RelationshipType.ValueType
    source_id: builtins.str
    """The Primary Key of the source node"""
    target_id: builtins.str
    """The Primary Key of the target node"""
    source_label: builtins.str
    """The label of the source node"""
    target_label: builtins.str
    """The label of the target node"""
    @property
    def properties(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        type: global___Relationship.RelationshipType.ValueType = ...,
        source_id: builtins.str = ...,
        target_id: builtins.str = ...,
        properties: google.protobuf.struct_pb2.Struct | None = ...,
        source_label: builtins.str = ...,
        target_label: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["properties", b"properties"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["properties", b"properties", "source_id", b"source_id", "source_label", b"source_label", "target_id", b"target_id", "target_label", b"target_label", "type", b"type"]) -> None: ...

global___Relationship = Relationship

@typing.final
class Project(google.protobuf.message.Message):
    """=======================================================
    Specific Node Payload Messages
    =======================================================
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Primary Key"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___Project = Project

@typing.final
class Package(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALIFIED_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    qualified_name: builtins.str
    """Primary Key"""
    name: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        qualified_name: builtins.str = ...,
        name: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "path", b"path", "qualified_name", b"qualified_name"]) -> None: ...

global___Package = Package

@typing.final
class Folder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    path: builtins.str
    """Primary Key"""
    name: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "path", b"path"]) -> None: ...

global___Folder = Folder

@typing.final
class File(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    EXTENSION_FIELD_NUMBER: builtins.int
    path: builtins.str
    """Primary Key"""
    name: builtins.str
    extension: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        name: builtins.str = ...,
        extension: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["extension", b"extension", "name", b"name", "path", b"path"]) -> None: ...

global___File = File

@typing.final
class Module(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALIFIED_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    qualified_name: builtins.str
    """Primary Key"""
    name: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        qualified_name: builtins.str = ...,
        name: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "path", b"path", "qualified_name", b"qualified_name"]) -> None: ...

global___Module = Module

@typing.final
class ModuleImplementation(google.protobuf.message.Message):
    """C++20 only"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALIFIED_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    IMPLEMENTS_MODULE_FIELD_NUMBER: builtins.int
    qualified_name: builtins.str
    """Primary Key"""
    name: builtins.str
    path: builtins.str
    implements_module: builtins.str
    def __init__(
        self,
        *,
        qualified_name: builtins.str = ...,
        name: builtins.str = ...,
        path: builtins.str = ...,
        implements_module: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["implements_module", b"implements_module", "name", b"name", "path", b"path", "qualified_name", b"qualified_name"]) -> None: ...

global___ModuleImplementation = ModuleImplementation

@typing.final
class ModuleInterface(google.protobuf.message.Message):
    """C++20 only"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALIFIED_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    qualified_name: builtins.str
    """Primary Key"""
    name: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        qualified_name: builtins.str = ...,
        name: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "path", b"path", "qualified_name", b"qualified_name"]) -> None: ...

global___ModuleInterface = ModuleInterface

@typing.final
class ExternalPackage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Primary Key"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___ExternalPackage = ExternalPackage

@typing.final
class Function(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALIFIED_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DOCSTRING_FIELD_NUMBER: builtins.int
    START_LINE_FIELD_NUMBER: builtins.int
    END_LINE_FIELD_NUMBER: builtins.int
    DECORATORS_FIELD_NUMBER: builtins.int
    IS_EXPORTED_FIELD_NUMBER: builtins.int
    qualified_name: builtins.str
    """Primary Key"""
    name: builtins.str
    docstring: builtins.str
    start_line: builtins.int
    end_line: builtins.int
    is_exported: builtins.bool
    @property
    def decorators(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        qualified_name: builtins.str = ...,
        name: builtins.str = ...,
        docstring: builtins.str = ...,
        start_line: builtins.int = ...,
        end_line: builtins.int = ...,
        decorators: collections.abc.Iterable[builtins.str] | None = ...,
        is_exported: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["decorators", b"decorators", "docstring", b"docstring", "end_line", b"end_line", "is_exported", b"is_exported", "name", b"name", "qualified_name", b"qualified_name", "start_line", b"start_line"]) -> None: ...

global___Function = Function

@typing.final
class Method(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALIFIED_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DOCSTRING_FIELD_NUMBER: builtins.int
    START_LINE_FIELD_NUMBER: builtins.int
    END_LINE_FIELD_NUMBER: builtins.int
    DECORATORS_FIELD_NUMBER: builtins.int
    qualified_name: builtins.str
    """Primary Key"""
    name: builtins.str
    docstring: builtins.str
    start_line: builtins.int
    end_line: builtins.int
    @property
    def decorators(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        qualified_name: builtins.str = ...,
        name: builtins.str = ...,
        docstring: builtins.str = ...,
        start_line: builtins.int = ...,
        end_line: builtins.int = ...,
        decorators: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["decorators", b"decorators", "docstring", b"docstring", "end_line", b"end_line", "name", b"name", "qualified_name", b"qualified_name", "start_line", b"start_line"]) -> None: ...

global___Method = Method

@typing.final
class Class(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALIFIED_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DOCSTRING_FIELD_NUMBER: builtins.int
    START_LINE_FIELD_NUMBER: builtins.int
    END_LINE_FIELD_NUMBER: builtins.int
    DECORATORS_FIELD_NUMBER: builtins.int
    IS_EXPORTED_FIELD_NUMBER: builtins.int
    qualified_name: builtins.str
    """Primary Key"""
    name: builtins.str
    docstring: builtins.str
    start_line: builtins.int
    end_line: builtins.int
    is_exported: builtins.bool
    @property
    def decorators(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        qualified_name: builtins.str = ...,
        name: builtins.str = ...,
        docstring: builtins.str = ...,
        start_line: builtins.int = ...,
        end_line: builtins.int = ...,
        decorators: collections.abc.Iterable[builtins.str] | None = ...,
        is_exported: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["decorators", b"decorators", "docstring", b"docstring", "end_line", b"end_line", "is_exported", b"is_exported", "name", b"name", "qualified_name", b"qualified_name", "start_line", b"start_line"]) -> None: ...

global___Class = Class
